### ISSUE TITLE
it's just a copy of https://github.com/bitcoin/bitcoin

### ISSUE THREAD

**Issue by wongoo** [v-dimension/vds-core#3]
there is not document introduce the vds，it's just a copy of https://github.com/bitcoin/bitcoin!!

**Comment by iDagger** [comment]
really?

**Comment by helo68** [comment]
那这个币还是属于没有真正开源对吗。是这样吗？有没有真正在做事。白皮书的内容能实现吗

**Comment by kittencup** [comment]
传销币 鉴定完毕
