### ISSUE TITLE
the vds node stopped to sync at 90347 height, how to resolve the issue.

### ISSUE THREAD

**Issue by anzhaozhong** [v-dimension/vds-core#9]
node conf:
ubuntu 16.04,
mem 32G, 
disk 800G,
cpus 4,

vds version:
[0.9.9](https://ipfs.io/ipfs/Qmca2tptodgq31pfEcebpER3byoSuXqkTd2fq7AyyfuijA)

I tried following methods, but not effective.
1. -reindex
2. add node
3. -checkblocks=10
4.rm blk???.dat

**Comment by qianchong88** [comment]
你是怎么同步的？我启动了一天了getinfo 显示blocks 还是 0

**Comment by v-dimension** [comment]
@anzhaozhong  Is your node synchronized yet?

**Comment by qianchong88** [comment]
> @anzhaozhong Is your node synchronized yet?

没有，还在同步，比特币块在增加，vds的块还是0

**Comment by v-dimension** [comment]
@qianchong88  just add some seeds to your vds.conf

**Comment by Feiox** [comment]
> 你是怎么同步的？我启动了一天了getinfo 显示blocks 还是 0

微信联系我，帮您建立钱包（包括数据、节点等）
